### ISSUE TITLE
snatcher throws exceptions when trying to serialize 'null' JSON property vals

### ISSUE THREAD

**Issue by scottkurz** [WASdev/sample.batch.tweetanalyzer#5]
Seems this is especially likely to happen with the user 'location' field (returned by `status.getUser().getLocation()`).

We see exception messages like this below and the object completely fails to serialize: 

```
Oct 24, 2018 4:24:47 PM org.eclipse.yasson.internal.Marshaller marshall
SEVERE: Problem adapting object of type interface twitter4j.Status to interface javax.json.JsonObject in class class com.ibm.websphere.sample.snatcher.StatusAdapter
Oct 24, 2018 4:24:47 PM org.eclipse.yasson.internal.Marshaller marshall
SEVERE: Generating incomplete JSON
javax.json.bind.JsonbException: Problem adapting object of type interface twitter4j.Status to interface javax.json.JsonObject in class class com.ibm.websphere.sample.snatcher.StatusAdapter
        at org.eclipse.yasson.internal.serializer.AdaptedObjectSerializer.serialize(AdaptedObjectSerializer.java:107)
        at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:118)
        at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
        at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:106)
        at com.ibm.websphere.sample.snatcher.TweetStatusFileWriter.write(TweetStatusFileWriter.java:110)
        at com.ibm.websphere.sample.snatcher.TweetSnatcher.main(TweetSnatcher.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
        at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:222)
        at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:90)
        at com.ibm.websphere.sample.snatcher.StatusAdapter.adaptToJson(StatusAdapter.java:47)
        at com.ibm.websphere.sample.snatcher.StatusAdapter.adaptToJson(StatusAdapter.java:14)
        at org.eclipse.yasson.internal.serializer.AdaptedObjectSerializer.serialize(AdaptedObjectSerializer.java:103)
        ... 11 more
```

**Comment by scottkurz** [comment]
Fixed well enough by bf712c2049b8074c6bd3e1b6584bbb3558c4cc1e
